name: A03 webhooks

on:
  push:
    branches:
      - master

jobs:
  build-push-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: charlieszafron/nodegoat-cs:latest

  semgrep-sast-scan:
    runs-on: itas276-cszafron
    container:
      image: returntocorp/semgrep

    steps:
      - uses: actions/checkout@v2

      - name: Run Semgrep and generate SARIF report
        run: |
          semgrep \
          --sarif --output semgrep-sast.sarif \
          --metrics=off \
          --config="p/default"

      - name: Save Semgrep SARIF report
        uses: actions/upload-artifact@v2
        with:
          name: semgrep-sast.sarif
          path: semgrep-sast.sarif

  snyk-scan:
    runs-on: itas276-cszafron
    steps:
      - uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        with:
          command: test
          args: --sarif-file-output=snyk-results.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Save Snyk SARIF report
        uses: actions/upload-artifact@v2
        with:
          name: snyk-sca.sarif
          path: snyk-results.sarif

  discord-notification:
    runs-on: ubuntu-latest
    needs: [build-push-scan, semgrep-sast-scan, snyk-scan]
    steps:
      - name: Post message to Discord
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "GitHub Actions"
          embed-title: "Workflow Status Update"
          embed-description: "The workflow has completed successfully."
          embed-color: "#00ff00" # Green color for success
          thread-id: ${{ github.run_id }} # Use the GitHub run ID as thread ID
