name: Charlie - ITAS276 - Assignment 1

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag charlieszafron/nodegoat-cs:latest

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push to Docker Hub
      run: |
        docker push charlieszafron/nodegoat-cs:latest

    - name: Remove previous private image (optional)
      run: docker rmi charlieszafron/nodegoat-cs:previous-tag
      continue-on-error: true
