name: Charlie - ITAS276 - Assignment 1

on:
  push:
    branches: 
      - master 

jobs:
  build:
    runs-on: itas276-cszafron

    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: charlieszafron/nodegoat-cs:latest

  semgrep-sast-scan:
    runs-on: itas276-cszafron
    container:
      image: returntocorp/semgrep
            
    steps:   
      - uses: actions/checkout@v2

      - name: Semgrep scan
        run: | 
          semgrep \
          --sarif --output semgrep-sast.sarif \
          --metrics=off \
          --config="p/default"

      - name: Save report
        uses: actions/upload-artifact@v2
        with:
          name: semgrep-sast.sarif
          path: semgrep-sast.sarif

  snyk-scan:
    runs-on: itas276-cszafron
    steps:
      - uses: actions/checkout@v2

      - name: Build a Docker image
        run: docker build -t charlieszafron/nodegoat-cs:latest .

      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_SECRET }}
        with:
          image: charlieszafron/nodegoat-cs:latest
          args: --severity-threshold=high --sarif-file-output=snyk-sca.sarif
        
      - name: Save report
        uses: actions/upload-artifact@v2
        with:
          name: snyk-sca.sarif
          path: snyk-sca.sarif
