name: Build docker image and deploy to wmd docker servers

on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]
    
jobs:
    
    deploy:
        name: "Deploy to ITAS WMD server"
        runs-on: [self-hosted, Linux, X64, itas276-cszafron]


        steps:
            -   name: Copy source code files
                uses: actions/checkout@v3

            -   name: Test files are visibile
                # Execute some shell commands on your server (this is the self-hosted instance)
                run: |
                    whoami
                    ls-lah
