name: A03 webhooks

on:
 push:
    branches: [ "master" ]
 pull_request:
    branches: [ "master" ]

jobs:
    # Post a message to the Discord channel with pipeline updates.
    NodeGoat-Discord-Notification:
      runs-on: ubuntu-latest
      steps:
       - name: Discord Notification
         uses: tsickert/discord-webhook@v5.3.0
         with:
           webhook-url: ${{ secrets.DISCORD_WEBHOOK }} # Use the webhook URL kept in secrets
           username: ${{ github.repository }}
           avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
           embed-title: "NodeGoat Pipeline jobs are starting..."
           embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
           embed-description: "[Action details ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
           embed-author-name: "${{ github.actor }}"
